apiVersion: v1
kind: Service
metadata:
  name: {{ include "deploy_chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "deploy_chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "deploy_chart.selectorLabels" . | nindent 4 }}
