- name: Download Calico manifest
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml
    dest: /tmp/calico.yaml
    mode: '0644'
  become: true

- name: Apply Calico manifest to the cluster
  ansible.builtin.command: kubectl apply -f /tmp/calico.yaml
  environment:
    KUBECONFIG: /home/systemadmin/.kube/config
  become: true