---
- name: Check if this node is already joined
  ansible.builtin.shell: |
    test -f /etc/kubernetes/kubelet.conf
  register: worker_joined
  failed_when: false
  changed_when: false
  become: true

- name: Fetch join command from master
  ansible.builtin.fetch:
    src: /join-command.sh
    dest: /tmp/join-command.sh
    flat: yes
  delegate_to: "{{ groups['masters'][0] }}"
  when: worker_joined.rc != 0
  become: true

- name: Join this node to cluster
  ansible.builtin.command: sh /tmp/join-command.sh
  when: worker_joined.rc != 0
  become: true