apiVersion: v1
kind: Service
metadata:
  name: {{ include "logging-system.fullname" . }}
  labels:
    {{- include "logging-system.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.fluentbit.type }}
  ports:
    - port: {{ .Values.service.fluentbit.port }}
      targetPort: {{ .Values.containerPort.fluentbit }}
      protocol: TCP
      name: http
  selector:
    {{- include "logging-system.selectorLabels" . | nindent 4 }}
